<a href="https://colab.research.google.com/github/JHBaek0306/BigData/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_1%EB%B6%80_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 3. 파이썬 기초

## 3-1. 파이썬 자료형

### 가. 숫자형(number)

In [ ]:
# 정수형, 실수형
a=123
b=-123.4
a+b

-0.4000000000000057

In [ ]:
# 8진수
c=0o34
d=0o24
c+d

48

In [ ]:
# 16진수
e=0x2A
f=0xFF
e+f

297

### 나. 문자형(String)

In [ ]:
# 문자열
s='WiseInCompany'
s1="WiseInCompany"
s2='''WiseInCompany'''
s3="123"
print(s)
print(s1)
print(s2)
print(s3)
print(type(s3))

WiseInCompany
WiseInCompany
WiseInCompany
123
<class 'str'>


In [ ]:
# 문자열 연산하기
a="Wise"
b="InCompany"
print(a+b)
a="WiseInCompany"
print(a*2)

WiseInCompany
WiseInCompanyWiseInCompany


In [ ]:
# 문자열 인덱싱 및 슬라이싱
a="Wise In Company"
print(a[3])
print(a[-3])
print(a[0:15])
print(a[4:])
print(a[0:4])

e
a
Wise In Company
 In Company
Wise


### 다. 리스트(List)

In [ ]:
# 리스트
a=[1,2,3,4,5]
print(a)
# 리스트 인덱싱
a=[1,2,3,4,5]
print(a[0])
print(a[-1])
# 리스트 슬라이싱
a=[1,2,3,4,5]
print(a[0:5])
print(a[:5])
print(a[2:])

[1, 2, 3, 4, 5]
1
5
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[3, 4, 5]


In [ ]:
# 리스트 요소 추가/수정/삭제
a=[1,2,3,4,5]
a.append(6)
a[0]=0
del a[1]
print(a)

[0, 3, 4, 5, 6]


In [ ]:
# 리스트 병합 및 반복
a=[1,2]
b=[3,4,5]
c=a+b
print(c)
d=a*3
print(d)

[1, 2, 3, 4, 5]
[1, 2, 1, 2, 1, 2]


### 라. 튜플(Tuple)

In [ ]:
# 튜플
t=(1,2,3,4,5)
# 튜플 인덱싱 및 슬라이싱
t1=(1,2,3)
print(t[1]) # 인덱싱
print(t[0:3]) # 슬라이싱

2
(1, 2, 3)


In [ ]:
# 튜플 병합 및 반복
a=(1,2)
b=(3,4,5)
c=a+b
print(d)
d=a*3
print(d)

[1, 2, 1, 2, 1, 2]
(1, 2, 1, 2, 1, 2)


In [ ]:
# 튜플 변수 할당
name=("David", "Kim")
print(name)
firstname, lastname=("David", "Kim")
print(lastname, ", ", firstname)

('David', 'Kim')
Kim ,  David


### 마. 집합(set)

In [ ]:
# 집합
set={1,1,2,3}
print(set)

{1, 2, 3}


In [ ]:
# 집합 추가 및 삭제1
set={1,1,2,3}
set.add(4) # 요소 하나 추가
set

{1, 2, 3, 4}

In [ ]:
# 집합 추가 및 삭제2
set={1,1,2,3}
set.update({4,5,6}) # 요소 여러 개 추가
set

{1, 2, 3, 4, 5, 6}

In [ ]:
# 요소 하나 삭제
set.remove(1)
set

{2, 3, 4, 5, 6}

In [ ]:
# 요소 모두 삭제
set.clear()
set

set()

In [ ]:
# 집합 연산
a={1,2,3}
b={1,3,4}
# 교집합
c=a&b
print(c)
# 합집합
d=a|b
print(d)
# 차집합
e=a-b
print(e)

{1, 3}
{1, 2, 3, 4}
{2}


### 바. 사전(Dictionary)

In [ ]:
# 사전
test={"Kim":90, "Jeong":80, "Park":75}
test["Kim"] # 키 이용

90

In [ ]:
# 사전 추가/수정/삭제
test={"Kim":90, "Jeong":80, "Park":75}
test["Jeong"]=85
test["Cho"]=95
del test["Park"]
print(test)

{'Kim': 90, 'Jeong': 85, 'Cho': 95}


In [ ]:
# 키 또는 값 가져오기
test={"Kim":90, "Jeong":80, "Park":75}
print(test.keys())    # 키 가져오기
print(test.values())  # 값 가져오기

dict_keys(['Kim', 'Jeong', 'Park'])
dict_values([90, 80, 75])


## 3-2. if문

In [ ]:
# if문 예시
money=4000
if money==3000:
    print("KTX 타고 가자")
elif money>=5000:
    print("버스 타고 가자")
else:
    print("걍 걸어가!")

걍 걸어가!


## 3-3. 반복문

### 가. for문

In [ ]:
# for문 기본
sum=0
for i in range(11):
    sum=sum+i
print(sum)

55


In [ ]:
# for문 리스트 출력
list=["Wise", "In", "Company"]
for s in list:
    print(s)

Wise
In
Company


### 나. while문

In [ ]:
# while문 기본
i=0
while i<10:
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9


In [ ]:
# while문 리스트 출력
food=["apple", "banana", "bread"]
i=0
while i < len(food):
    print(food[i])
    i=i+1

apple
banana
bread


# 4. numpy 함수

### 가. numpy 배열 생성

In [ ]:
# numpy 배열 기본
import numpy as np
v1=np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [ ]:
# 연속되거나 일정한 규칙을 가진 숫자
v1=np.arange(5)
print(v1)
# 연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2=np.arange(1,10,2, dtype=int)
v3=np.arange(3.5,10.5,2, dtype=float)
print(v2)
print(v3)
# 제곱값 생성
v4=np.arange(1,10,2)**2
print(v4)
# 세제곱값 생성
v5=np.arange(1,10,2)**3
print(v5)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


In [ ]:
# 행렬만들기
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,6)
print(v2)
v3=v1.reshape(2,6, order='F')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [ ]:
# 행렬계산
v1=np.arange(1,5).reshape(2,2)
print(np.add(v1,v1))        # 덧셈
print(np.subtract(v1,v1))   # 뺄셈
print(np.multiply(v1,v1))   # 곱셈
print(np.dot(v1,v1))        # 행렬연산

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
# 다차원 행렬 만들기
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,3,2, order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
# 다차원 배열에서 요소의 최대값 및 최소값 반환
v3=np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4=np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amin(v4))
print(v3.dtype)
print(v4.shape)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)


# 5. pandas 함수와 기본 데이터 처리

## 5.1 pandas 함수 개요
### 나. Series

In [ ]:
# pandas 함수 불러오기
import pandas as pd
from pandas import Series, DataFrame
# series 설정
a=Series([1,3,5,7])
print(a)
print(a.values)
print(a.index)
# index 변경
a2=pd.Series([1,3,5,7], index=['a','b','c', 'd'])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64


In [ ]:
# index 변경
a2=pd.Series([1,3,5,7], index=['a','b','c', 'd'])
a2

a    1
b    3
c    5
d    7
dtype: int64

## 5.2 데이터 불러오기

### 가. DataFrame과 데이어 파일 불러오기

In [ ]:
# csv파일을 pandas DataFrame 형태로 불러오기
df=pd.read_csv('EX_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [ ]:
# 엑셀파일을 pandas DataFrame 형태로 불러오기
df=pd.read_excel('EX_GrapeData.xlsx')
df

continent  brand  size  period  price
0           2      2  10.7   47.65  144.0
1           2      3  14.0   63.13  215.0
2           2      2   9.0   58.76  105.0
3           1      1   8.0   34.88   69.0
4           2      2  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

[63 rows x 5 columns]

In [ ]:
# 한글이 포함되어 있을 경우 인코딩 설정(encoding='euc-kr', 'cp949', 'utf-8' 등 옵션 설정)
# df = pd.read_csv('EX_GrapeData.csv', encoding='euc-kr')
# df = pd.read_excel('EX_GrapeData.xlsx', encoding='euc-kr')

### 나. DataFrame 확인하기

In [ ]:
# 데이터 프레임 처음부터 ~개의 행만 불러오기
df.head()

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0

In [ ]:
# 데이터 프레임 뒤부터 ~개의 행만 불러오기
df.tail()

continent  brand  size  period  price
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

In [ ]:
# 1에서 4까지 출력
df[1:5]

continent  brand  size  period  price
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0

In [ ]:
# 처음부터 2까지 출력
df[:3]

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0

In [ ]:
# 60에서 끝까지 출력
df[60:]

continent  brand  size  period  price
60          2      2   5.0    12.0    NaN
61          2      3  13.0    20.0    NaN
62          2      3  31.0    19.0    NaN

In [ ]:
# price 변수(열) 불러오기: series 형태
df['price'] # df.price으로 대체 가능

0     144.0
1     215.0
2     105.0
3      69.0
4     134.0
      ...  
58     21.5
59      NaN
60      NaN
61      NaN
62      NaN
Name: price, Length: 63, dtype: float64

In [ ]:
# price 변수(열) 불러오기: DataFrame 형태
df[['price']]

price
0   144.0
1   215.0
2   105.0
3    69.0
4   134.0
..    ...
58   21.5
59    NaN
60    NaN
61    NaN
62    NaN

[63 rows x 1 columns]

In [ ]:
# 0번, 2번, 4번째 열(컬럼)만 출력
df[df.columns[[0,2,4]]]

continent  size  price
0           2  10.7  144.0
1           2  14.0  215.0
2           2   9.0  105.0
3           1   8.0   69.0
4           2  10.0  134.0
..        ...   ...    ...
58          1   5.0   21.5
59          2  21.0    NaN
60          2   5.0    NaN
61          2  13.0    NaN
62          2  31.0    NaN

[63 rows x 3 columns]

In [ ]:
# size부터 price까지 출력
df.loc[:, 'size':'price']

size  period  price
0   10.7   47.65  144.0
1   14.0   63.13  215.0
2    9.0   58.76  105.0
3    8.0   34.88   69.0
4   10.0   55.53  134.0
..   ...     ...    ...
58   5.0   16.66   21.5
59  21.0   43.00    NaN
60   5.0   12.00    NaN
61  13.0   20.00    NaN
62  31.0   19.00    NaN

[63 rows x 3 columns]

In [ ]:
# 1~7행(케이스), 0~2열(변수)만 불러오기
df.iloc[1:7, 0:2]

continent  brand
1          2      3
2          2      2
3          1      1
4          2      2
5          2      2
6          2      2

In [ ]:
# 5행(케이스)의 price 변수 해당 값 불러오기
df.at[5, 'price']

129.0

## 5.3 데이터 변환하기

### 가. 복사, 추가, 삭제

In [ ]:
#데이터 프레임 전체 복사 (백업)
df_columns = df.copy()

In [ ]:
#데이터 프레임의 열(변수) 이름 확인
df_columns.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [ ]:
#데이터 프레임 열 필터링
df_columns = df_columns[['size','period','price']]
df_columns.head()

size  period  price
0  10.7   47.65  144.0
1  14.0   63.13  215.0
2   9.0   58.76  105.0
3   8.0   34.88   69.0
4  10.0   55.53  134.0

### 나. 변수이름 변경, 행추가 및 삭제

In [ ]:
# 데이터 열(변수) 이름 수정: period -> time
df_columns.rename(columns={'period': 'time'}, inplace=True)
df_columns.columns

Index(['size', 'time', 'price'], dtype='object')

In [ ]:
# size를 time으로 나누어 월별 포도크기로 계산하여 growth 변수 생성
df_columns['growth']=df_columns['size']/df_columns['time']
df_columns.head()

size   time  price    growth
0  10.7  47.65  144.0  0.224554
1  14.0  63.13  215.0  0.221765
2   9.0  58.76  105.0  0.153165
3   8.0  34.88   69.0  0.229358
4  10.0  55.53  134.0  0.180083

In [ ]:
# 특정 변수 삭제: growth 삭제
del df_columns['growth']

### 다. 데이터 케이스 추출

In [ ]:
# 특정 케이스 선택1: 집단선택
df_continent_brand=df[(df['continent']==1) & (df['brand']==1)]
df_continent_brand.head()

continent  brand  size  period  price
3           1      1   8.0   34.88   69.0
11          1      1  10.4   17.67   54.0
12          1      1   7.4   16.41   39.0
13          1      1   5.4   12.02   29.5
16          1      1   6.0   23.21   42.0

In [ ]:
# 특정 케이스 선택2: 기준값 이상 혹은 이하 선택
df_over_size_period=df[(df['size']>=10) & (df['period']>=30)]
df_over_size_period.head()

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
4          2      2  10.0   55.53  134.0
5          2      2  10.5   43.14  129.0
6          2      2  16.0   54.86  155.0

### 라. 코딩변경

In [ ]:
df_columns.head()

size   time  price
0  10.7  47.65  144.0
1  14.0  63.13  215.0
2   9.0  58.76  105.0
3   8.0  34.88   69.0
4  10.0  55.53  134.0

In [ ]:
# brand 범주 카운트
df['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

- 방법1) replace 사용

In [ ]:
# brand 1, 2, 3 집단을 1, 2로 묶기 (1/2 ->1, 3->2)
recode_brand = {"brand": {1: 1, 2: 1, 3: 2}}

In [ ]:
df_recode1 = df.replace(recode_brand)
df_recode1.head()

continent  brand  size  period  price
0          2      1  10.7   47.65  144.0
1          2      2  14.0   63.13  215.0
2          2      1   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      1  10.0   55.53  134.0

In [ ]:
df_recode1['brand'].value_counts()

1    47
2    16
Name: brand, dtype: int64

- 방법2) 함수정의 사용

In [ ]:
# 코딩변경 함수 정의
def brand_groups(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2

df['re_brand']=df['brand'].apply(brand_groups)
df.head()

continent  brand  size  period  price  re_brand
0          2      2  10.7   47.65  144.0         1
1          2      3  14.0   63.13  215.0         2
2          2      2   9.0   58.76  105.0         1
3          1      1   8.0   34.88   69.0         1
4          2      2  10.0   55.53  134.0         1

### 마. pandas와 numpy 전환

In [ ]:
# pandas 형태로 데이터 불러와서 확인
import pandas as pd
df=pd.read_csv('EX_GrapeData.csv')
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [ ]:
# pandas를 numpy로 변환
df_num=df.to_numpy()
df_num

array([[2, 2, 10.7, 47.65, '144'],
       [2, 3, 14.0, 63.13, '215'],
       [2, 2, 9.0, 58.76, '105'],
       [1, 1, 8.0, 34.88, '69'],
       [2, 2, 10.0, 55.53, '134'],
       [2, 2, 10.5, 43.14, '129'],
       [2, 2, 16.0, 54.86, '155'],
       [2, 1, 15.0, 44.14, '99'],
       [2, 1, 6.5, 17.46, '38.5'],
       [2, 1, 5.0, 21.04, '36.5'],
       [2, 2, 25.0, 109.38, '260'],
       [1, 1, 10.4, 17.67, '54'],
       [1, 1, 7.4, 16.41, '39'],
       [1, 1, 5.4, 12.02, '29.5'],
       [2, 2, 15.4, 49.48, '109'],
       [2, 1, 12.4, 48.74, '89.5'],
       [1, 1, 6.0, 23.21, '42'],
       [1, 1, 9.0, 28.64, '65'],
       [1, 3, 9.0, 44.95, '115'],
       [1, 1, 12.4, 23.77, '49.5'],
       [1, 1, 7.5, 20.21, '36.5'],
       [1, 3, 14.0, 32.62, '109'],
       [1, 1, 7.0, 17.84, '45'],
       [1, 2, 9.0, 22.82, '58'],
       [1, 2, 12.0, 29.48, '89'],
       [1, 1, 5.5, 15.61, '30'],
       [1, 2, 6.0, 13.25, '31'],
       [1, 3, 12.0, 45.78, '119'],
       [2, 1, 5.5, 26.53, '22'],
     

In [ ]:
# numpy를 pandas로 변환 (변수명 미지정)
df_pd = pd.DataFrame(df_num)
df_pd.head()

0  1     2      3    4
0  2  2  10.7  47.65  144
1  2  3  14.0  63.13  215
2  2  2   9.0  58.76  105
3  1  1   8.0  34.88   69
4  2  2  10.0  55.53  134

In [ ]:
# numpy를 pandas로 변환 (변수명 지정)
df_pd2 = pd.DataFrame(data = df_num, columns = ["continent", "brand", "size", "period", "price"])
df_pd2.head()

continent brand  size period price
0         2     2  10.7  47.65   144
1         2     3  14.0  63.13   215
2         2     2   9.0  58.76   105
3         1     1   8.0  34.88    69
4         2     2  10.0  55.53   134

### 바. csv파일로 저장

In [ ]:
# 데이터셋명.to_csv("새로운파일명.csv", index=True/False, encoding='utf-8'/'euc-kr', 'cp949')
df.to_csv('new_data.csv', index=False, encoding='utf-8')